import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/common/header";
import Footer from "@/app/common/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "DheyWang Bhutan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
      >
        <Header />
        <main>
          <div className="fixed top-1/3 right-0 flex flex-col space-y-4 p-2 bg-gray-100 rounded-r-lg shadow-lg">
            {[1, 2, 3, 4].map(
              (v => (
                <a
                  href="https://www.instagram.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center justify-center w-10 h-10 bg-white text-black rounded-full shadow hover:text-indigo-600 hover:bg-gray-100"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    fill="currentColor"
                    className="w-6 h-6"
                  >
                    <path d="M12 2.163c3.204 0 3.584.012 4.85.07 1.256.058 2.09.276 2.578.465a5.372 5.372 0 011.89 1.146 5.372 5.372 0 011.146 1.89c.189.488.407 1.322.465 2.578.058 1.267.07 1.647.07 4.85s-.012 3.584-.07 4.85c-.058 1.256-.276 2.09-.465 2.578a5.372 5.372 0 01-1.146 1.89 5.372 5.372 0 01-1.89 1.146c-.488.189-1.322.407-2.578.465-1.267.058-1.647.07-4.85.07s-3.584-.012-4.85-.07c-1.256-.058-2.09-.276-2.578-.465a5.372 5.372 0 01-1.89-1.146 5.372 5.372 0 01-1.146-1.89c-.189-.488-.407-1.322-.465-2.578-.058-1.267-.07-1.647-.07-4.85s.012-3.584.07-4.85c.058-1.256.276-2.09.465-2.578a5.372 5.372 0 011.146-1.89 5.372 5.372 0 011.89-1.146c.488-.189 1.322-.407 2.578-.465C8.416 2.175 8.796 2.163 12 2.163m0-2.163C8.74 0 8.332.012 7.052.07 5.77.129 4.743.319 3.85.6 2.857.902 2.04 1.36 1.33 2.07.62 2.78.162 3.597.06 4.59.019 5.49 0 5.896 0 9.163s.012 3.584.07 4.85c.058 1.256.276 2.09.465 2.578a7.368 7.368 0 001.146 1.89 7.368 7.368 0 001.89 1.146c.488.189 1.322.407 2.578.465 1.267.058 1.647.07 4.85.07s3.584-.012 4.85-.07c1.256-.058 2.09-.276 2.578-.465a7.368 7.368 0 001.89-1.146 7.368 7.368 0 001.146-1.89c.189-.488.407-1.322.465-2.578.058-1.267.07-1.647.07-4.85s-.012-3.584-.07-4.85c-.058-1.256-.276-2.09-.465-2.578a7.368 7.368 0 00-1.146-1.89 7.368 7.368 0 00-1.89-1.146c-.488-.189-1.322-.407-2.578-.465C15.584.012 15.204 0 12 0z"></path>
                  </svg>
                </a>
              ))
            )}
            {/* Add more icons */}
          </div>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
